INSERT INTO EMPLOYEE (
FIRST_NAME,LAST_NAME,LAST_UPDATED_BY,LAST_UPDATED_TS
) VALUES (
  'Pawan',
  'Choure',
  'PAWAN',
  '20210210'
);
INSERT INTO EMPLOYEE (
FIRST_NAME,LAST_NAME,LAST_UPDATED_BY,LAST_UPDATED_TS
) VALUES (
  'Akshay',
  'Bade',
  'Akshay',
  '20210210'
);
INSERT INTO DEPARTMENT (
DEPARTMENT_NAME,LAST_UPDATED_BY,LAST_UPDATED_TS
) VALUES (
  'IT',
  'Pawan',
  '20210210'
);
INSERT INTO DEPARTMENT (
DEPARTMENT_NAME,LAST_UPDATED_BY,LAST_UPDATED_TS
) VALUES (
  'COMPUTER',
  'Akshay',
  '20210210'
);